import { aiService } from "./aiService";
import { TextLine, ParseProfile } from "../types";

export const aiProfileService = {
  generateProfile: async (textLines: TextLine[], fileName: string): Promise<Partial<ParseProfile>> => {
    // Take a sample of text lines for analysis
    const sampleText = textLines
      .slice(0, 100)
      .map(l => l.text)
      .join('\n');

    const prompt = `
      Analyze the following text extracted from a timber takeoff document: "${fileName}".
      Identify the structure of the document and suggest a parsing profile.
      
      Specifically, identify:
      1. Section Header Patterns: Regex patterns that identify section headers (e.g., "GROUND FRAME", "ROOF TRUSSES").
      2. Ignore Patterns: Regex patterns for noise like page numbers, dates, or contact info.
      3. Unit Rules: Rules to assign default units (L/M, EA, m2) based on section names.
      
      Text Sample:
      ${sampleText}
      
      Return the result as a JSON object matching this schema:
      {
        "name": "Suggested Name",
        "description": "Brief description",
        "keywords": ["keyword1", "keyword2"],
        "serializedSettings": {
          "sectionHeaderPatterns": ["regex1", "regex2"],
          "ignorePatterns": ["regex1", "regex2"],
          "unitRules": [
            { "sectionNamePattern": "regex", "defaultUnit": "L/M" | "EA" | "m2" }
          ]
        }
      }
    `;

    try {
      const response = await aiService.generateContent({
        model: "gemini-3-flash-preview",
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: "OBJECT",
            properties: {
              name: { type: "STRING" },
              description: { type: "STRING" },
              keywords: { type: "ARRAY", items: { type: "STRING" } },
              serializedSettings: {
                type: "OBJECT",
                properties: {
                  sectionHeaderPatterns: { type: "ARRAY", items: { type: "STRING" } },
                  ignorePatterns: { type: "ARRAY", items: { type: "STRING" } },
                  unitRules: {
                    type: "ARRAY",
                    items: {
                      type: "OBJECT",
                      properties: {
                        sectionNamePattern: { type: "STRING" },
                        defaultUnit: { type: "STRING", enum: ["L/M", "EA", "m2"] }
                      },
                      required: ["sectionNamePattern", "defaultUnit"]
                    }
                  }
                },
                required: ["sectionHeaderPatterns", "ignorePatterns"]
              }
            },
            required: ["name", "description", "serializedSettings"]
          }
        }
      });

      const result = JSON.parse(response.text || '{}');
      return {
        id: `ai-${Math.random().toString(36).substr(2, 9)}`,
        name: result.name || 'AI Generated Profile',
        description: result.description || 'Automatically generated by Gemini',
        keywords: result.keywords || [],
        serializedSettings: result.serializedSettings,
        isCustom: true
      };
    } catch (error) {
      console.error("AI Profile Generation failed", error);
      throw error;
    }
  }
};
