import JSZip from 'jszip';
import * as XLSX from 'xlsx';
import { ParsedLine, ExportTemplate, FileMetadata, HistoryItem } from '../types';
import { applyTemplate } from './excelService';
import { calculateDiff, generateDiffCsv } from './comparison';

export const generateExportPack = async (
    data: ParsedLine[],
    metadata: FileMetadata | null,
    template: ExportTemplate,
    history: HistoryItem[],
    jobNotes: string
): Promise<Blob> => {
    const zip = new JSZip();
    const safeName = (metadata?.name || 'export').replace(/[^a-z0-9]/gi, '_');
    
    // 1. ERP CSV
    const erpData = applyTemplate(data, template, metadata);
    const erpSheet = XLSX.utils.json_to_sheet(erpData);
    const erpCsv = XLSX.utils.sheet_to_csv(erpSheet);
    zip.file(`${safeName}_ERP_Import.csv`, erpCsv);

    // 2. Assumptions Summary
    const summaryText = `
JOB SUMMARY
----------------------------
File: ${metadata?.name}
Builder: ${metadata?.builder || 'N/A'}
Site: ${metadata?.address || 'N/A'}
Job #: ${metadata?.jobNumber || 'N/A'}
Date: ${new Date().toLocaleString()}

STATS
----------------------------
Total Items: ${data.length}
Total Linear: ${data.filter(d => d.unit === 'L/M').reduce((a,b) => a + b.total, 0).toFixed(2)}m
Sections: ${new Set(data.map(d => d.section)).size}

JOB NOTES
----------------------------
${jobNotes || 'No notes found.'}

GENERATED BY
----------------------------
Timber Takeoff Converter
Template Used: ${template.name}
    `.trim();
    zip.file(`${safeName}_Summary.txt`, summaryText);

    // 3. Diff Report (Automatic)
    // Find previous versions with same Job Number OR similar filename
    const previous = history.filter(h => 
        h.id !== metadata?.name && // Not current (conceptually)
        h.timestamp < Date.now() &&
        (
            (metadata?.jobNumber && h.metadata?.jobNumber === metadata.jobNumber) ||
            (h.fileName.replace(/\.(pdf|xlsx?|csv)$/i, '').includes(safeName.split('_')[0])) // Rough name match
        )
    ).sort((a, b) => b.timestamp - a.timestamp)[0];

    if (previous) {
        const diffData = calculateDiff(previous.data, data);
        if (diffData.length > 0) {
            const diffCsv = generateDiffCsv(diffData, previous.fileName, 'Current Import');
            zip.file(`${safeName}_Delta_Report.csv`, diffCsv);
        }
    }

    return await zip.generateAsync({ type: 'blob' });
};